FROM golang:1.21.7-alpine3.19 as builder
WORKDIR /app
COPY ./ ./
RUN go build -o web_app ./cmd/web

FROM alpine:3.19 AS prod
WORKDIR /app
COPY --from=builder /app/web_app /app/
ENTRYPOINT ["/app/web_app"]
