FROM golang:1.21.7-alpine3.19 as builder
WORKDIR /app
COPY ./ ./
RUN go build -o inventory_service ./cmd/inventory

FROM alpine:3.19 AS prod
WORKDIR /app
COPY --from=builder /app/inventory_service /app/
COPY --from=builder /app/migrations /app/migrations
ENTRYPOINT ["/app/inventory_service"]
